sonar.projectKey=sonar-to-jira
sonar.projectName=Sonar to Jira
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.exclusions=.venv/**,venv/**,__pycache__/**,.ruff_cache/**,.git/**
