#!/usr/bin/env python3
# Copyright (c) 2026 Calfus Inc.
# Author: Wasiullah Rafeeq S
# Editor: Prakrit Mohanty

"""
Generates/merges .env: a random Postgres password, a fresh Fernet key, and
free host ports (scripts/env_ports.py). Run once per machine/checkout,
before `docker compose up` - and safe to re-run any time, since it only
ever fills in fields that are still missing.

Field-by-field, not all-or-nothing: an existing .env is never overwritten
key-by-key - each of POSTGRES_USER/PASSWORD/DB/HOST, the ports, and
FERNET_KEY is filled in independently if (and only if) it's missing.

The core logic lives in importable functions (resolve_ports, bootstrap_env)
- gozu's `init` wizard calls these directly so it can show the user the
chosen ports and let them override before anything is written to disk,
rather than just running this script as a subprocess.
"""

import argparse
import secrets
import sys
from datetime import UTC, datetime

from cryptography.fernet import Fernet

from scripts.env_ports import (
    DEFAULT_PORTS,
    ENV_PATH,
    load_into_environ,
    parse_env_file,
    resolve_ports,
)
from scripts.fernet_safety import FernetKeySafetyError, fernet_key_safety_check

__all__ = [
    "DEFAULT_PORTS",
    "ENV_PATH",
    "FernetKeySafetyError",
    "bootstrap_env",
    "load_into_environ",
    "parse_env_file",
    "resolve_ports",
]


def bootstrap_env(force_new_key: bool = False, port_overrides: dict[str, int] | None = None) -> dict[str, str]:
    """
    Fill in whatever fields are missing from .env (creating it if it
    doesn't exist yet). Returns the dict of fields that were newly written
    (empty if .env already had everything). `port_overrides` lets a caller
    (the init wizard) supply user-chosen ports instead of the auto-probed
    defaults, for ports not already present in .env.

    Raises FernetKeySafetyError instead of writing FERNET_KEY if that
    would orphan existing encrypted rows (see scripts/fernet_safety.py).
    """
    existing = parse_env_file(ENV_PATH)
    ports = resolve_ports()
    if port_overrides:
        ports.update(port_overrides)

    new_fields: dict[str, str] = {}

    if "POSTGRES_USER" not in existing:
        new_fields["POSTGRES_USER"] = "gozu"
    if "POSTGRES_PASSWORD" not in existing:
        new_fields["POSTGRES_PASSWORD"] = secrets.token_urlsafe(32)
    if "POSTGRES_DB" not in existing:
        new_fields["POSTGRES_DB"] = "gozu"
    if "POSTGRES_HOST" not in existing:
        new_fields["POSTGRES_HOST"] = "localhost"
    # A separate role/database for local-mode SonarQube's own Postgres
    # backend (sql/init_sonarqube_db.sql), in the same Postgres instance
    # as gozu's own database - genuinely isolated (a different database,
    # not a schema), so `gozu down --wipe`'s reset of gozu's own database
    # (cli/stack/wipe.py) can never touch it.
    if "SONARQUBE_DB_PASSWORD" not in existing:
        new_fields["SONARQUBE_DB_PASSWORD"] = secrets.token_urlsafe(32)

    for port_name in DEFAULT_PORTS:
        if port_name not in existing:
            new_fields[port_name] = str(ports[port_name])

    resolved = {**existing, **new_fields}

    if "TEMPORAL_HOST" not in existing:
        new_fields["TEMPORAL_HOST"] = f"localhost:{resolved['TEMPORAL_PORT']}"

    if "FERNET_KEY" not in existing:
        fernet_key_safety_check(resolved, force_new_key)
        new_fields["FERNET_KEY"] = Fernet.generate_key().decode()

    if not new_fields:
        return {}

    try:
        ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
        with ENV_PATH.open("a") as f:
            if not existing:
                f.write("# Generated by scripts/bootstrap_env.py - do not commit this file.\n")
            timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%SZ")
            f.write(f"\n# --- Added by bootstrap_env.py on {timestamp} ---\n")
            for key, value in new_fields.items():
                f.write(f"{key}={value}\n")
    except OSError as e:
        raise OSError(f"Failed to write {ENV_PATH}: {e}") from e

    return new_fields


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force-new-key",
        action="store_true",
        help="Allow generating a new FERNET_KEY even if Postgres already has encrypted config "
        "rows (those rows become permanently unreadable - you'll be asked to confirm).",
    )
    args = parser.parse_args()

    try:
        new_fields = bootstrap_env(force_new_key=args.force_new_key)
    except FernetKeySafetyError as e:
        print(f"Refusing to generate a new FERNET_KEY: {e}", file=sys.stderr)
        return 1
    except OSError as e:
        print(str(e), file=sys.stderr)
        return 1

    if not new_fields:
        print(f"{ENV_PATH} already has every required field - nothing to do.")
        return 0

    print(f"Updated {ENV_PATH}. New fields:")
    for key, value in new_fields.items():
        if key in ("POSTGRES_PASSWORD", "SONARQUBE_DB_PASSWORD", "FERNET_KEY"):
            print(f"  {key}: generated (not shown)")
        else:
            print(f"  {key}={value}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
