#!/usr/bin/env python3
"""
Generates a .env with a random Postgres password and a fresh Fernet key.
Run once per machine/checkout, before `docker compose up`.

Idempotent: refuses to overwrite an existing .env (its Postgres password and
FERNET_KEY are load-bearing for whatever's already in the database - a fresh
FERNET_KEY makes every previously-encrypted config value permanently
unreadable, and a fresh Postgres password locks out the existing volume's
data until it's updated to match).
"""

import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"

ENV_TEMPLATE = """\
# Generated by scripts/bootstrap_env.py - do not commit this file.

# --- Postgres ---
POSTGRES_USER=sonarjira
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=sonarjira
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

# --- Encryption ---
# Fernet key used to encrypt/decrypt secrets stored in the configs table
# (sonar_token, jira_api_token, webhook_secret). Losing this key makes every
# encrypted value in the database permanently unrecoverable - back it up
# somewhere safe outside of version control.
FERNET_KEY={fernet_key}

# --- Temporal ---
# Overridden to temporal:7233 for the worker container by docker-compose.yml;
# this default is for running the worker directly on the host.
TEMPORAL_HOST=localhost:7233
"""


def main() -> int:
    if ENV_PATH.exists():
        print(f".env already exists at {ENV_PATH} - leaving it untouched.")
        return 0

    postgres_password = secrets.token_urlsafe(32)
    fernet_key = Fernet.generate_key().decode()

    ENV_PATH.write_text(
        ENV_TEMPLATE.format(postgres_password=postgres_password, fernet_key=fernet_key)
    )

    print(f"Wrote {ENV_PATH}")
    print("Generated: POSTGRES_PASSWORD, FERNET_KEY")
    print("Set: POSTGRES_USER=sonarjira, POSTGRES_DB=sonarjira, POSTGRES_HOST=localhost, POSTGRES_PORT=5432, TEMPORAL_HOST=localhost:7233")
    print("(Fill in SonarQube/Jira credentials separately - not part of this bootstrap step.)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
